#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
    branches: [main, "v[12].[0-9]+-[a-zA-Z]*"]
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ${{ github.repository_owner == 'duckdb' && 'namespace-profile-linux-slim' || 'ubuntu-slim' }}
    name: Prepare
    outputs:
      runners: ${{ steps.runners.outputs.runners }}
    steps:
      - name: Detect runners
        id: runners
        uses: duckdb/duckdb-ci/detect-runners@main

  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    needs: prepare
    with:
      extension_name: &ext_name azure
      ci_tools_version: &ci_tools_ref main
      runners: ${{ needs.prepare.outputs.runners }}
      exclude_archs: &exclude_archs wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools;windows_amd64_mingw

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@main
    secrets: inherit
    with:
      extension_name: *ext_name
      ci_tools_version: *ci_tools_ref
      exclude_archs: *exclude_archs
      deploy_latest: ${{ startsWith(github.ref, 'refs/heads/v') || github.ref == 'refs/heads/main' }}
      deploy_versioned: ${{ startsWith(github.ref, 'refs/heads/v') || github.ref == 'refs/heads/main' }}

  code-quality-check:
    name: Code Quality Check
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_code_quality.yml@main
    with:
      extension_name: *ext_name
      duckdb_version: 1a779c5c43100f162d19237e3cf3e64f36bc3485
      ci_tools_version: *ci_tools_ref
      # TODO: format_checks += ;tidy
      format_checks: format
      extra_toolchains: "python3"
